import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;

  return (
    <div className="flex gap-3">
      <img
        className="h-14 w-14 rounded-full"
        src={user.imageUrl}
        alt="Profile image"
      />
      <input
        placeholder="type some emojis!"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

export default function Home() {
  const user = useUser();
  console.log(user);

  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>
          <div className="">
            {[...data, ...data]?.map(({ post, author }) => (
              <div
                className="flex gap-6 border-b border-slate-400 p-8"
                key={post.id}
              >
                <img src={author?.imageUrl} className="h-8 w-8" />
                <div className="flex items-center gap-3">
                  <span>{post.content}</span>
                  <span>{author?.username}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
